### ISSUE TITLE
Sources don't persist

### ISSUE THREAD

**Issue by luke3butler** [alexrozanski/LlamaChat#1]
After closing the app and reopening it, the chat sources are cleared out and need to be re-added.

My steps:
1. Opened app, and added Alpaca in GGML format.
2. Used the app for a bit.
3. Closed the app.
4. Opened app, and got prompted to add a source again. Previous addition disappeared.

**Comment by alexrozanski** [comment]
Thanks for the report, @luke3butler. Couple of things here:

- Could you check if `~/Library/Application Support/com.alexrozanski.LlamaChat/sources.json` exists? This is where the sources should be persisted to.
- I just [pushed](https://github.com/alexrozanski/LlamaChat/commit/a5692e629b74cc7a7ac2364ae0bbc96cedd2f652) a temporary fix to add some more logging to diagnose what's going on here - I'll release a new build of the app within the next day or two with any new changes (so you can see what's going on from Console.app), but if you've built from source then any errors should now be logged to the console in Xcode.

**Comment by alexrozanski** [comment]
ah got it, there was a bug in the chat source deserialisation logic. fixed in 1fafb1f, will release an update shortly. for now, a workaround is to make sure to select an avatar when adding a source.

thanks for the reports!

**Comment by alexrozanski** [comment]
Fixed in v1.0.1: https://github.com/alexrozanski/LlamaChat/releases/tag/1.0.1
