### ISSUE TITLE
Request for support of official OpenAI API for ChatGPT/GPT4

### ISSUE THREAD

**Issue by sksq96** [alexrozanski/LlamaChat#11]
I am reaching out to request support for the official OpenAI API for ChatGPT/GPT4 in LlamaChat. I understand that the current Llama models are designed to run offline, but I believe that adding support for faster APIs would make the software more native to Mac and ultimately, more useful.

I kindly ask you to consider adding the official OpenAI API for ChatGPT/GPT4 in LlamaChat. Thank you for your time and consideration.

**Comment by alexrozanski** [comment]
Hey @sksq96, thanks for your feedback. This is definitely something I've thought about, but for now LlamaChat is focusing on the local LLaMA family of models, and there are a lot of other tools which already exist which wrap ChatGPT, like http://macgpt.com.

Gonna close this for now but will reconsider if there's more support for this in the future!
