### ISSUE TITLE
Ensure messages view is scrolled to bottom when new messages are added

### ISSUE THREAD

**Issue by martinverhey** [alexrozanski/LlamaChat#18]
When you're at the bottom of the chat, it should focus on showing the generated text, as it's being generated. Which means, it should automatically scroll to a new line as it's being generated.

Now the newly generated messages go off-screen at the bottom and you have to manually scroll continuously to read each line as it's being generated.

Same goes for showing your own message at the bottom when pressing enter.

**Comment by alexrozanski** [comment]
Hey @martinverhey, thanks for filing! I tried to get this to work (there is a temporary implementation here: https://github.com/alexrozanski/LlamaChat/blob/main/LlamaChat/ui/chat/messages/MessagesView.swift#L61) but the messages view needs reimplementing as there's no built-in way to do this in SwiftUI.

Will get to this soon ✌️

**Comment by alexrozanski** [comment]
Fixed in v1.2.0
