### ISSUE TITLE
I also want to use versions of Mac 13 and below, and I hope to support the use of Mac computers under Mac 13

### ISSUE THREAD

**Issue by MrYangyt** [alexrozanski/LlamaChat#20]
I also want to use versions of Mac 13 and below, and I hope to support the use of Mac computers under Mac 13

**Comment by alexrozanski** [comment]
Thanks @MrYangyt - supporting versions < macOS 13 isn't on the roadmap right now, but will keep this open to track it in case this changes.

**Comment by newbie-lad** [comment]
If you want a support of a computer that you have bought, you should not stick with _Apple._ They make money selling them, not providing you what you want.
(No support of ‘obsolete’ systems needed. They are doomed anyway.)
I loved first generation 27″ Imac, but you know what _it is worth_ now?

**Comment by alexrozanski** [comment]
Closing this as don't have the resources, and also (hopefully) will become less relevant with the release of Sonoma
