### ISSUE TITLE
Can the questions not affect each other?

### ISSUE THREAD

**Issue by waywayliu** [alexrozanski/LlamaChat#25]
I have observed that the previous questions affect the results of the later questions, and each question is not independent of the other. Is there a way to make them independent of each other?
Thank you.

**Comment by alexrozanski** [comment]
hey @hunxuewangzi, there's a 'clear context' button at the bottom next to the compose field which will clear the model's current context:

<img width="1183" alt="Screenshot 2023-04-23 at 20 38 32" src="https://user-images.githubusercontent.com/170472/233861315-d89fecc7-4a6a-4112-9541-2b7f376bb71e.png">

it's not super clear I know, will work on making this a bit more obvious!

also you mention that you want each question to be independent of the other -- i'm curious about your use case here: is this when changing topics or you want each question to be completely separate from the previous one?

**Comment by waywayliu** [comment]
Thanks for your answer, but I don't see that button.
<img width="696" alt="截屏2023-04-24 11 01 44" src="https://user-images.githubusercontent.com/80691681/233890817-fd7692d2-018d-4d7d-aec7-9820f54cf916.png">

I want each question to be completely separate from the previous one

**Comment by waywayliu** [comment]
@alexrozanski

**Comment by alexrozanski** [comment]
@hunxuewangzi It only appears when there is context to clear - chat context is automatically cleared between launches because it's not saved anywhere. But if you launch the app and send a message you should see it once you receive a response. Is that the case for you?

**Comment by waywayliu** [comment]
@alexrozanski  I understand, thanks!
