### ISSUE TITLE
Selected Model is Unsupported

### ISSUE THREAD

**Issue by xavierallem** [alexrozanski/LlamaChat#3]
**Using Alpaca and gpt4all**

Have the following 

-  ggml-alpaca-7b-q4.bin 
-  gpt4all-lora-quantized.bin

After selecting the path it shows `Selected model is of an unsupported version`

<img width="609" alt="image" src="https://user-images.githubusercontent.com/60181637/231417362-6509fed1-f042-42e6-b04c-2d84f1516fd6.png">

**Comment by alexrozanski** [comment]
Hey @xavierallem, sorry - the docs and UI aren't super clear on this yet. Looks like you have one of the slightly older model versions. I'm going to add native flows for these cases, but for now you can use:

- [convert-unversioned-ggml-to-ggml.py](https://github.com/ggerganov/llama.cpp/blob/cbef542879962fdc491656cd0c8cadd65a5f1356/convert-unversioned-ggml-to-ggml.py) for the Alpaca model
- [convert-gpt4all-to-ggml.py](https://github.com/ggerganov/llama.cpp/blob/master/convert-gpt4all-to-ggml.py) for the GPT4All model

from the llama.cpp repo to upgrade the models to the new format required by llama.cpp (which LlamaChat uses internally). Lmk if this works!

**Comment by alexrozanski** [comment]
added some details to the README for now

**Comment by danieldunderfelt** [comment]
The instructions are quite obtuse. The convert script wants a tokenizer.model, where can I get this? Only google results are some random huggingface things which I am not comfortable touching.

**Comment by alexrozanski** [comment]
@danieldunderfelt good feedback. I added some more notes in https://github.com/alexrozanski/LlamaChat/blob/main/README.md#-models, but this should really be better supported/documented in the conversion flow

**Comment by danieldunderfelt** [comment]
> @danieldunderfelt good feedback. I added some more notes in https://github.com/alexrozanski/LlamaChat/blob/main/README.md#-models, but this should really be better supported/documented in the conversion flow

Epic, thanks!

**Comment by alexrozanski** [comment]
This is fixed in v1.2.0 -- older models are now supported directly in LlamaChat.
