### ISSUE TITLE
Support closing add source view with dedicated cancel button

### ISSUE THREAD

**Issue by crystoneme** [alexrozanski/LlamaChat#7]
when I open the software, but without load any models, I can't find anywhere to exit.
Until I forced to kill it in the system setting.
![Screenshot 2023-04-13 at 09 09 47](https://user-images.githubusercontent.com/8197573/231620028-befa2208-28f7-4682-b474-9662ea66129d.jpg)

**Comment by alexrozanski** [comment]
Hey @crystoneme - yeah this isn't ideal - the window is presented as a standard macOS sheet which can only be dismissed with the Esc key. Let me look into improving this though, I could add a dedicated close button perhaps.

**Comment by alexrozanski** [comment]
@crystoneme this is fixed in 8f203df, will release this soon!
<img width="673" alt="Screenshot 2023-04-14 at 01 06 22" src="https://user-images.githubusercontent.com/170472/231908892-05f1006b-e741-49da-9edc-dea3fb216f7b.png">

**Comment by alexrozanski** [comment]
Fixed in v1.2.0
