### ISSUE TITLE
Chinese LLaMA/Alpaca is currently working.

### ISSUE THREAD

**Issue by fakechris** [alexrozanski/LlamaChat#8]
I'v tried add an Alpaca model, select quanted Chinese alpaca model generated by https://colab.research.google.com/drive/1Eak6azD3MLeb-YsfbP8UZC8wrL1ddIMI?usp=sharing, It worked very well.

Thanks for your great work!

![chinese_llama](https://user-images.githubusercontent.com/8452/231648313-08b01dcd-3797-4f8d-b32e-018e5d4bb04f.jpg)

**Comment by alexrozanski** [comment]
Thanks @fakechris, good to hear! Yep, LlamaChat will technically supports any LLaMA model - surfacing support for different models (with default configurations etc) is coming soon.
